import { StyleSheet } from 'aphrodite'

export const styles = StyleSheet.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '400px',
    minWidth: '250px',
    height: '200px',
    minHeight: '100px',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    cursor: 'pointer',
    border: 0,
    borderRadius: '10px',
    margin: 20,
    padding: 20,
    justifyContent: 'space-between',
  },
  rootDisabled: {
    display: 'flex',
    flexDirection: 'column',
    width: '400px',
    minWidth: '250px',
    height: '200px',
    minHeight: '100px',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    opacity: 0.4,
    border: 0,
    borderRadius: '10px',
    cursor: 'not-allowed',
    pointerEvents: 'none',
    margin: 20,
    padding: 20,
    justifyContent: 'space-between',
  },
  header: {},
  info: {
    justifyContent: 'flex-end',
  },
})
